title = "Loft Dynamics Config"

[outputvariables]
# StateName = {Variable, # of digits to round to, description that shows up on second line of data file}
# If no precision value, default will be used

aircraft_type = "r22"
Datetime = "" #NO EDIT
comments = "" #NO EDIT

Aerofly_Out_Aircraft_Latitude =  { state_id = 2496586604, description = "Latitude (rad) (double)"} 
Aerofly_Out_Aircraft_Longitude =  { state_id = 1666704728, description = "Longitude (rad) (double)"} 
